# Generated by Django 3.1.3 on 2020-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201223_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer',
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_and_returns',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Featured', 'Featured'), ('Promo', 'Promo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, null=True),
        ),
    ]
