# Generated by Django 3.1.3 on 2020-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201223_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('New', 'New'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
