# Generated by Django 3.1.3 on 2020-12-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201228_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingshop',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
