# Generated by Django 3.1.3 on 2021-01-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201229_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gallery/items')),
                ('subject', models.CharField(max_length=12)),
                ('content', models.CharField(max_length=20)),
                ('other', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Advertisement Section',
            },
        ),
        migrations.CreateModel(
            name='SubAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='gallery/items')),
                ('subject', models.CharField(max_length=12)),
                ('content', models.CharField(max_length=20)),
                ('other', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Sub Adverts',
            },
        ),
        migrations.AlterModelOptions(
            name='billingshop',
            options={'verbose_name_plural': 'BILLING ADDRESS'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
