# Generated by Django 3.1.3 on 2021-01-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210101_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name_plural': 'ADVERTISEMENT SECTION'},
        ),
        migrations.AlterModelOptions(
            name='subadvert',
            options={'verbose_name_plural': 'SUB ADVERTS'},
        ),
        migrations.AddField(
            model_name='advert',
            name='mobile_pic',
            field=models.ImageField(default='mobile-slide.jpg', upload_to='gallery/items'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
