# Generated by Django 3.1.3 on 2021-01-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210101_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('False', 'False'), ('True', 'True')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, default='20', max_length=10, null=True),
        ),
    ]
